# Generated by Django 5.0 on 2023-12-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0004_remove_medicine_box_size_remove_medicine_cost_price_and_more'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_id', models.CharField(max_length=100)),
                ('expiry', models.DateField()),
                ('entry', models.DateField(auto_now_add=True)),
                ('box_size', models.IntegerField()),
                ('box_cp', models.FloatField(verbose_name='Box Cost')),
                ('box_sp', models.FloatField(verbose_name='Box Sell')),
                ('tabs_strip', models.IntegerField()),
                ('strip_cp', models.FloatField(verbose_name='Strip Cost')),
                ('strip_sp', models.FloatField(verbose_name='Strip Sell')),
                ('tabs_cp', models.FloatField(verbose_name='Piece Cost')),
                ('tabs_sp', models.FloatField(verbose_name='Piece Sell')),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
