# Generated by Django 5.0 on 2023-12-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_remove_medicine_box_size_remove_medicine_cost_price_and_more'),
        ('purchase', '0001_initial'),
        ('stocks', '0002_stocks'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Purchase_details',
        ),
    ]
