# Generated by Django 5.0 on 2023-12-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_purchase_purchase_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_details',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
