# Generated by Django 5.0 on 2023-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_details_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
