# Generated by Django 5.0 on 2023-12-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_details_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
