# Generated by Django 5.0 on 2024-01-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_remove_medicine_box_size_remove_medicine_cost_price_and_more'),
        ('purchase', '0006_yourmodel'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='batch_id',
            field=models.CharField(help_text='Batch ID of the purchased medicine', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='box_cp',
            field=models.FloatField(help_text='Cost price of the entire box', verbose_name='Box Cost'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='box_size',
            field=models.IntegerField(help_text='Number of strips per box'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='box_sp',
            field=models.FloatField(help_text='Selling price of the entire box', verbose_name='Box Sell'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='entry',
            field=models.DateField(auto_now_add=True, help_text='Date of purchase entry'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='expiry',
            field=models.DateField(blank=True, help_text='Expiry date of the medicine', null=True),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='medicine_name',
            field=models.ForeignKey(help_text='Medicine being purchased', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of medicine purchased'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='strip_cp',
            field=models.FloatField(help_text='Cost price of a strip', verbose_name='Strip Cost'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='strip_sp',
            field=models.FloatField(help_text='Selling price of a strip', verbose_name='Strip Sell'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier of the medicine', on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='tabs_cp',
            field=models.FloatField(help_text='Cost price of a tablet', verbose_name='Piece Cost'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='tabs_sp',
            field=models.FloatField(help_text='Selling price of a tablet', verbose_name='Piece Sell'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='tabs_strip',
            field=models.IntegerField(help_text='Number of tablets per strip'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='unique_id',
            field=models.IntegerField(blank=True, help_text='Unique identifier for the purchase details', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='description',
            field=models.TextField(help_text='Description of the model'),
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='name',
            field=models.CharField(help_text='Name of the model', max_length=100),
        ),
    ]
