# Generated by Django 5.0 on 2023-12-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order_order_no'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='orderpos',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='orderpos',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderpos',
            name='unit',
        ),
        migrations.AddField(
            model_name='order',
            name='batch_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stocks.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpos',
            name='date_entry',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpos',
            name='order_no',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
