# Generated by Django 5.0 on 2023-12-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('medicine', '0003_remove_medicine_unit_alter_medicine_strength'),
        ('pos', '0003_remove_order_order_no_remove_orderpos_batch_id_and_more'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_entry',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=30)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.batch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
            ],
        ),
        migrations.AddField(
            model_name='pos',
            name='order_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.orderitem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderPOS',
        ),
    ]
