# Generated by Django 5.0 on 2023-12-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('medicine', '0003_remove_medicine_unit_alter_medicine_strength'),
        ('pos', '0004_remove_order_order_id_remove_order_batch_id_and_more'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_entry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
        migrations.AddField(
            model_name='order',
            name='batch_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stocks.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pos.pos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='medicine_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='date_entry',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='order_id',
            field=models.ManyToManyField(through='pos.Order', to='medicine.medicine'),
        ),
        migrations.AddField(
            model_name='pos',
            name='order_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
