# Generated by Django 5.0 on 2023-12-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='order_no',
            field=models.IntegerField(unique=True),
        ),
    ]
