# Generated by Django 5.0 on 2023-12-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_pos_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
                ('pos_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.pos')),
            ],
        ),
    ]
