# Generated by Django 5.0 on 2023-12-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_invoice_order_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pos_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.pos'),
        ),
    ]
