# Generated by Django 5.0 on 2023-12-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_invoice_pos_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='date_entry',
            field=models.DateField(auto_now=True),
        ),
    ]
