# Generated by Django 5.0 on 2024-01-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_return_returndetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.invoice'),
        ),
    ]
