# Generated by Django 5.0 on 2024-01-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_returndetails_quantity_returndetails_returned_item'),
        ('stocks', '0010_stocks_pieces_stocks_strips'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndetails',
            name='batch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.batch'),
            preserve_default=False,
        ),
    ]
