# Generated by Django 5.0 on 2024-01-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_returndetails_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='date',
        ),
    ]
