# Generated by Django 5.0 on 2024-01-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_phone'),
        ('medicine', '0004_remove_medicine_box_size_remove_medicine_cost_price_and_more'),
        ('pos', '0017_return_date'),
        ('stocks', '0010_stocks_pieces_stocks_strips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pos_order',
            field=models.OneToOneField(help_text='POS order associated with the invoice', on_delete=django.db.models.deletion.CASCADE, to='pos.pos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='batch_id',
            field=models.ForeignKey(help_text='Batch of the medicine', on_delete=django.db.models.deletion.CASCADE, to='stocks.batch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Order to which the item belongs', on_delete=django.db.models.deletion.CASCADE, to='pos.pos', verbose_name='Order_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='medicine_name',
            field=models.ForeignKey(help_text='Medicine included in the order', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of the medicine in the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(help_text='Unit of measurement for the quantity', max_length=30),
        ),
        migrations.AlterField(
            model_name='pos',
            name='customer_id',
            field=models.ForeignKey(help_text='Customer placing the order', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='date_entry',
            field=models.DateField(auto_now=True, help_text='Date of order entry'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='order_id',
            field=models.ManyToManyField(help_text='Medicines included in the order', through='pos.Order', to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='order_no',
            field=models.IntegerField(help_text='Unique order number for identification', unique=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Date of return'),
        ),
        migrations.AlterField(
            model_name='return',
            name='invoice_no',
            field=models.ForeignKey(help_text='Invoice associated with the returned items', on_delete=django.db.models.deletion.CASCADE, to='pos.invoice'),
        ),
        migrations.AlterField(
            model_name='returndetails',
            name='batch_id',
            field=models.ForeignKey(help_text='Batch of the returned medicine', on_delete=django.db.models.deletion.CASCADE, to='stocks.batch'),
        ),
        migrations.AlterField(
            model_name='returndetails',
            name='inv_number',
            field=models.ForeignKey(help_text='Return associated with the invoice', on_delete=django.db.models.deletion.CASCADE, to='pos.return', verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='returndetails',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of the returned medicine'),
        ),
        migrations.AlterField(
            model_name='returndetails',
            name='returned_item',
            field=models.ForeignKey(help_text='Medicine returned', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
    ]
