# Generated by Django 5.0.1 on 2024-01-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_invoice_pos_order_alter_order_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
    ]
