# Generated by Django 5.0.1 on 2024-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_entry',
            field=models.DateField(auto_now=True, help_text='Date of invoice entry', null=True),
        ),
    ]
