# Generated by Django 5.0.1 on 2024-01-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_alter_invoice_date_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_entry',
        ),
    ]
