# Generated by Django 5.0.1 on 2024-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_remove_invoice_date_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_entry',
            field=models.DateField(blank=True, help_text='Date of invoice entry', null=True),
        ),
    ]
