# Generated by Django 5.0.1 on 2024-01-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_alter_invoice_date_entry'),
        ('stocks', '0011_alter_batch_batch_id_alter_batch_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Date of return')),
                ('batch_id', models.ForeignKey(help_text='Batch of the returned medicine', on_delete=django.db.models.deletion.CASCADE, to='stocks.batch')),
                ('medicine_name', models.ForeignKey(help_text='Stock returned', on_delete=django.db.models.deletion.CASCADE, to='stocks.stocks')),
            ],
        ),
    ]
