# Generated by Django 5.0.1 on 2024-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_returnpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpurchase',
            name='last_purchase_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnpurchase',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity of the returned medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnpurchase',
            name='supplier_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnpurchase',
            name='unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnpurchase',
            name='medicine_name',
            field=models.CharField(max_length=150),
        ),
    ]
