# Generated by Django 5.0.1 on 2024-02-07 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_returndetails_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndetails',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of return'),
            preserve_default=False,
        ),
    ]
