# Generated by Django 5.0 on 2023-12-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('strength', models.CharField(max_length=50)),
                ('generic_name', models.CharField(max_length=150)),
                ('box_size', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('cost_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturer')),
                ('med_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine_type')),
            ],
        ),
    ]
