# Generated by Django 5.0 on 2023-12-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='tabs_strip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
