# Generated by Django 5.0 on 2023-12-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_tabs_strip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='unit',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
