# Generated by Django 5.0 on 2023-12-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_remove_medicine_unit_alter_medicine_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='box_size',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='tabs_strip',
        ),
    ]
