# Generated by Django 5.0 on 2023-12-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '__first__'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Box number')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.batch', verbose_name='batch')),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase', verbose_name='medicine name')),
            ],
        ),
    ]
