# Generated by Django 5.0 on 2023-12-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_details_unique_id'),
        ('stocks', '0002_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='stocks',
            name='last_purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase_details', verbose_name='last_purchase'),
            preserve_default=False,
        ),
    ]
