# Generated by Django 5.0 on 2023-12-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stocks_medicine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='medicine_name',
        ),
    ]
