# Generated by Django 5.0 on 2023-12-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stocks_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='entry_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
