# Generated by Django 5.0 on 2023-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_stocks_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='pieces',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piece number'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='strips',
            field=models.IntegerField(blank=True, null=True, verbose_name='Strip number'),
        ),
    ]
