# Generated by Django 5.0 on 2024-01-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_remove_medicine_box_size_remove_medicine_cost_price_and_more'),
        ('purchase', '0007_alter_purchase_details_batch_id_and_more'),
        ('stocks', '0010_stocks_pieces_stocks_strips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(help_text='Unique identifier for the batch', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='entry',
            field=models.DateField(auto_now_add=True, help_text='Date of batch entry'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry',
            field=models.DateField(help_text='Expiry date of the batch'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='batch_id',
            field=models.ForeignKey(blank=True, help_text='Batch associated with the stock', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.batch', verbose_name='batch'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='entry_date',
            field=models.DateField(blank=True, help_text='Date of stock entry', null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='last_purchase',
            field=models.ForeignKey(help_text='Last purchase details associated with the stock', on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase_details', verbose_name='last_purchase'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='medicine_name',
            field=models.ForeignKey(help_text='Medicine associated with the stock', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='pieces',
            field=models.IntegerField(blank=True, help_text='Number of pieces in stock', null=True, verbose_name='Piece number'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of boxes in stock', null=True, verbose_name='Box number'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='strips',
            field=models.IntegerField(blank=True, help_text='Number of strips in stock', null=True, verbose_name='Strip number'),
        ),
    ]
